# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
   configuration: conf.py

formats:
    - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
    install:
        - requirements: requirements.txt
