! <CM_ChemGroups_mod.f90 - A component of the EMEP MSC-W Chemical transport Model, version rv4.36>
!*****************************************************************************!
!*
!*  Copyright (C) 2007-2020 met.no
!*
!*  Contact information:
!*  Norwegian Meteorological Institute
!*  Box 43 Blindern
!*  0313 OSLO
!*  NORWAY
!*  email: emep.mscw@met.no
!*  http://www.emep.int
!*
!*    This program is free software: you can redistribute it and/or modify
!*    it under the terms of the GNU General Public License as published by
!*    the Free Software Foundation, either version 3 of the License, or
!*    (at your option) any later version.
!*
!*    This program is distributed in the hope that it will be useful,
!*    but WITHOUT ANY WARRANTY; without even the implied warranty of
!*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!*    GNU General Public License for more details.
!*
!*    You should have received a copy of the GNU General Public License
!*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
!*****************************************************************************!
! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem19a PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis Pollen
module ChemGroups_mod

  use ChemSpecs_mod        ! => species indices
  use OwnDataTypes_mod  ! => typ_sp, typ_factors, typ_maps
  
  implicit none
  private
  character(len=*),parameter, public :: CM_schemes_ChemGroups = " EmChem19a PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis Pollen"
  
  
  ! Assignment of groups from GenIn_Species.csv
  public :: Init_ChemGroups
  
  type(typ_sp), dimension(305), public, save :: chemgroups
  type(typ_factors), dimension(2), public, save :: chemgroups_factors
  type(typ_maps), dimension(1), public, save :: chemgroups_maps
  
  integer, public, target, save, dimension (12) :: &
    RO2_GROUP = (/  &
      CH3O2, C2H5O2, C4H9O2, ISRO2, ETRO2, PRRO2, OXYO2, MEKO2,  &
      C5DICARBO2, MACRO2, CH3CO3, TERPO2  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    DAOBS_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DAOBS_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    OX_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_OX_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (3) :: &
    NOX_GROUP = (/ NO, NO2, shipNOx /)
  
  integer, public, target, save, dimension (15) :: &
    OXN_GROUP = (/  &
      NO, NO2, NO3, N2O5, HONO, HNO3, HO2NO2, SC4H9NO3, NALD,  &
      ISON, PAN, MPAN, NO3_f, NO3_c, shipNOx  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_NOX_GROUP = (/ NO2, shipNOx /)
  
  integer, public, target, save, dimension (13) :: &
    DDEP_OXN_GROUP = (/  &
      NO2, N2O5, HONO, HNO3, HO2NO2, SC4H9NO3, NALD, ISON, PAN,  &
      MPAN, NO3_f, NO3_c, shipNOx  &
    /)
  
  integer, public, target, save, dimension (8) :: &
    WDEP_OXN_GROUP = (/ N2O5, HONO, HNO3, HO2NO2, NALD, ISON, NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P0E5_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P0E5_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P0E5_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (2) :: &
    F0_1P0_GROUP = (/ H2O2, HO2NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_F0_1P0_GROUP = (/ H2O2, HO2NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_F0_1P0_GROUP = (/ H2O2, HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P36_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_1P36_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P36_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P6E5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P6E5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P6E5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (2) :: &
    F0_0P5_GROUP = (/ HONO, PAN /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_F0_0P5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_F0_0P5_GROUP = (/ HONO, PAN /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_1P6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P0E4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_6P0E4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_6P0E4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_2P1_GROUP = (/ HO2NO2, CH3CHO, GLYOX /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_2P1_GROUP = (/ HO2NO2, GLYOX /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_2P1_GROUP = (/ HO2NO2, CH3CHO, GLYOX /)
  
  integer, public, target, save, dimension (2) :: &
    BVOC_GROUP = (/ C5H8, APINENE /)
  
  integer, public, target, save, dimension (11) :: &
    RCHO_GROUP = (/  &
      HCHO, CH3CHO, MACR, GLYOX, MGLYOX, C5DICARB, C5DICAROOH,  &
      HPALD, MACROOH, PACALD, NALD  &
    /)
  
  integer, public, target, save, dimension (9) :: &
    WDEP_RCHO_GROUP = (/  &
      HCHO, GLYOX, MGLYOX, C5DICARB, C5DICAROOH, HPALD, MACROOH,  &
      PACALD, NALD  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_RCHO_GROUP = (/  &
      HCHO, CH3CHO, MACR, GLYOX, MGLYOX, C5DICARB, C5DICAROOH,  &
      HPALD, MACROOH, PACALD, NALD  &
    /)
  
  integer, public, target, save, dimension (15) :: &
    CARBONYL_GROUP = (/  &
      HCHO, CH3CHO, MACR, MEK, ACETOL, GLYOX, MGLYOX, BIACET,  &
      C5DICARB, MEKO2H, C5DICAROOH, HPALD, MACROOH, PACALD, NALD  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    WDEP_CARBONYL_GROUP = (/  &
      HCHO, ACETOL, GLYOX, MGLYOX, C5DICARB, MEKO2H, C5DICAROOH,  &
      HPALD, MACROOH, PACALD, NALD  &
    /)
  
  integer, public, target, save, dimension (15) :: &
    DDEP_CARBONYL_GROUP = (/  &
      HCHO, CH3CHO, MACR, MEK, ACETOL, GLYOX, MGLYOX, BIACET,  &
      C5DICARB, MEKO2H, C5DICAROOH, HPALD, MACROOH, PACALD, NALD  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P2E3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P2E3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P2E3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (9) :: &
    F0_0P2_GROUP = (/  &
      HCHO, MGLYOX, CH3OOH, C2H5OOH, ETRO2H, OXYO2H, CH3CO3H,  &
      MPAN, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    WDEP_F0_0P2_GROUP = (/ HCHO, MGLYOX, ETRO2H, OXYO2H, CH3CO3H, TERPOOH /)
  
  integer, public, target, save, dimension (9) :: &
    DDEP_F0_0P2_GROUP = (/  &
      HCHO, MGLYOX, CH3OOH, C2H5OOH, ETRO2H, OXYO2H, CH3CO3H,  &
      MPAN, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_1P4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P3E1_GROUP = (/ CH3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P3E1_GROUP = (/ CH3CHO /)
  
  integer, public, target, save, dimension (5) :: &
    F0_0P05_GROUP = (/ CH3CHO, MACR, MEK, ACETOL, BIACET /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_F0_0P05_GROUP = (/ CH3CHO, MACR, MEK, ACETOL, BIACET /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P0E0_GROUP = (/ MACR /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_5P0E0_GROUP = (/ MACR /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P6_GROUP = (/ MACR, ACETOL /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_2P6_GROUP = (/ MACR, ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P0E1_GROUP = (/ MEK /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P0E1_GROUP = (/ MEK /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P7_GROUP = (/ MEK, NALD /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_2P7_GROUP = (/ MEK, NALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P0E3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_8P0E3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_8P0E3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_F0_0P05_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P6_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P0E5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P0E5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P0E5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    F0_0P0_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_F0_0P0_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_F0_0P0_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P4E4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P4E4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P4E4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P5_GROUP = (/ MGLYOX, ETRO2H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_2P5_GROUP = (/ MGLYOX, ETRO2H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_2P5_GROUP = (/ MGLYOX, ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_7P3E1_GROUP = (/ BIACET /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_7P3E1_GROUP = (/ BIACET /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P8_GROUP = (/ BIACET, PAN /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_2P8_GROUP = (/ BIACET, PAN /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P0E5_GROUP = (/ C5DICARB /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_6P0E5_GROUP = (/ C5DICARB /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_6P0E5_GROUP = (/ C5DICARB /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_3P1_GROUP = (/ C5DICARB, MEKO2H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_3P1_GROUP = (/ C5DICARB, MEKO2H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_3P1_GROUP = (/ C5DICARB, MEKO2H /)
  
  integer, public, target, save, dimension (11) :: &
    ROOH_GROUP = (/  &
      CH3OOH, C2H5OOH, BURO2H, ETRO2H, MEKO2H, ISRO2H, C5DICAROOH,  &
      HPALD, MACROOH, OXYO2H, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_ROOH_GROUP = (/  &
      CH3OOH, C2H5OOH, BURO2H, ETRO2H, MEKO2H, ISRO2H, C5DICAROOH,  &
      HPALD, MACROOH, OXYO2H, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P0E2_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P0E2_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P9_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P9_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P3E2_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P3E2_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P3_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_2P3_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P2E1_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_6P2E1_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P0_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P0_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (8) :: &
    WDEP_ROOH_GROUP = (/  &
      ETRO2H, MEKO2H, ISRO2H, C5DICAROOH, HPALD, MACROOH, OXYO2H,  &
      TERPOOH  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P3E6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P3E6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P3E6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_9P0E4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_9P0E4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_9P0E4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P6E8_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P6E8_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P6E8_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P55_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P55_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P55_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (3) :: &
    F0_0P3_GROUP = (/ C5DICAROOH, SC4H9NO3, ISON /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_F0_0P3_GROUP = (/ C5DICAROOH, ISON /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_F0_0P3_GROUP = (/ C5DICAROOH, SC4H9NO3, ISON /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P2E5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P2E5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P2E5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_3P3_GROUP = (/ HPALD, SC4H9NO3 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P3_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_3P3_GROUP = (/ HPALD, SC4H9NO3 /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P2_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P2_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P2_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P5E8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P5E8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P5E8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P4E8_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P4E8_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P4E8_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_4P1_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_4P1_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_4P1_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (2) :: &
    PEROXYACID_GROUP = (/ CH3CO3H, PACALD /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_PEROXYACID_GROUP = (/ CH3CO3H, PACALD /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_PEROXYACID_GROUP = (/ CH3CO3H, PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P3E2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_8P3E2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_8P3E2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P4_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P4_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_2P4_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (2) :: &
    HSTAR_1P5E6_GROUP = (/ PACALD, TERPOOH /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_HSTAR_1P5E6_GROUP = (/ PACALD, TERPOOH /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_HSTAR_1P5E6_GROUP = (/ PACALD, TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P47_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P47_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P47_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    EPOXIDE_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_EPOXIDE_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_EPOXIDE_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_0P0E0_GROUP = (/ SC4H9NO3 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_0P0E0_GROUP = (/ SC4H9NO3 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P5E3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_5P5E3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_5P5E3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P7_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P0E4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_5P0E4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_5P0E4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (2) :: &
    PANS_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_PANS_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    HSTAR_3P0E0_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_HSTAR_3P0E0_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P4_GROUP = (/ MPAN /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P4_GROUP = (/ MPAN /)
  
  integer, public, target, save, dimension (1) :: &
    MONOTERP_GROUP = (/ APINENE /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_4P5_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_4P5_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_4P5_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (4) :: &
    SOX_GROUP = (/ SO2, SO4, pSO4f, pSO4c /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_SOX_GROUP = (/ SO2, SO4, pSO4f, pSO4c /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_SOX_GROUP = (/ SO2, SO4, pSO4f, pSO4c /)
  
  integer, public, target, save, dimension (30) :: &
    PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, OM25_p, ffire_BC, ffire_remPPM25,  &
      ffire_c, SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c,  &
      Dust_wb_f, Dust_wb_c, Dust_sah_f, Dust_sah_c, Ash_f, Ash_c,  &
      POM_c_wood, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      pSO4f, pSO4c, remPPM25, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    WDEP_PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, ffire_BC, ffire_remPPM25, ffire_c,  &
      SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c, Dust_wb_f,  &
      Dust_wb_c, Dust_sah_f, Dust_sah_c, Ash_f, Ash_c,  &
      POM_c_wood, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      pSO4f, pSO4c, remPPM25, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    DDEP_PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, ffire_BC, ffire_remPPM25, ffire_c,  &
      SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c, Dust_wb_f,  &
      Dust_wb_c, Dust_sah_f, Dust_sah_c, Ash_f, Ash_c,  &
      POM_c_wood, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      pSO4f, pSO4c, remPPM25, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (17) :: &
    PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, OM25_p, ffire_BC, ffire_remPPM25,  &
      SeaSalt_f, Dust_road_f, Dust_wb_f, Dust_sah_f, Ash_f,  &
      EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (16) :: &
    WDEP_PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, ffire_BC, ffire_remPPM25, SeaSalt_f,  &
      Dust_road_f, Dust_wb_f, Dust_sah_f, Ash_f, EC_f_wood_new,  &
      EC_f_wood_age, EC_f_ffuel_new, EC_f_ffuel_age, pSO4f,  &
      remPPM25  &
    /)
  
  integer, public, target, save, dimension (16) :: &
    DDEP_PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, ffire_BC, ffire_remPPM25, SeaSalt_f,  &
      Dust_road_f, Dust_wb_f, Dust_sah_f, Ash_f, EC_f_wood_new,  &
      EC_f_wood_age, EC_f_ffuel_new, EC_f_ffuel_age, pSO4f,  &
      remPPM25  &
    /)
  
  integer, public, target, save, dimension (4) :: &
    SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    PNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_PNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_PNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (11) :: &
    PMCOARSE_GROUP = (/  &
      NO3_c, ffire_c, SeaSalt_c, Dust_road_c, Dust_wb_c,  &
      Dust_sah_c, Ash_c, POM_c_wood, POM_c_ffuel, pSO4c, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    WDEP_PMCOARSE_GROUP = (/  &
      NO3_c, ffire_c, SeaSalt_c, Dust_road_c, Dust_wb_c,  &
      Dust_sah_c, Ash_c, POM_c_wood, POM_c_ffuel, pSO4c, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_PMCOARSE_GROUP = (/  &
      NO3_c, ffire_c, SeaSalt_c, Dust_road_c, Dust_wb_c,  &
      Dust_sah_c, Ash_c, POM_c_wood, POM_c_ffuel, pSO4c, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (25) :: &
    OM25_GROUP = (/  &
      OM25_bgnd, ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2,  &
      ASOC_ug1e3, non_C_ASOA_ng1e2, non_C_ASOA_ug1,  &
      non_C_ASOA_ug10, non_C_ASOA_ug1e2, non_C_ASOA_ug1e3,  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, ffire_OM, POM_f_wood,  &
      POM_f_ffuel, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    NONVOLPCM_GROUP = (/  &
      OM25_bgnd, ffire_OM, ffire_BC, POM_f_wood, POM_c_wood,  &
      POM_f_ffuel, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    NVABSOM_GROUP = (/ OM25_bgnd, ffire_OM, POM_f_wood, POM_f_ffuel, SQT_SOA_NV /)
  
  integer, public, target, save, dimension (2) :: &
    OC_GROUP = (/ OM25_p, ffire_OM /)
  
  integer, public, target, save, dimension (24) :: &
    WDEP_OM25_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, POM_f_wood, POM_f_ffuel,  &
      SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (24) :: &
    DDEP_OM25_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, POM_f_wood, POM_f_ffuel,  &
      SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    PCM_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, ffire_BC, POM_f_wood,  &
      POM_f_ffuel, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    WDEP_PCM_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, ffire_BC, POM_f_wood,  &
      POM_f_ffuel, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    DDEP_PCM_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, ffire_BC, POM_f_wood,  &
      POM_f_ffuel, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    ASOA_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    WDEP_ASOA_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    DDEP_ASOA_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    BSOA_GROUP = (/  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    WDEP_BSOA_GROUP = (/  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_BSOA_GROUP = (/  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    TMPX_GROUP = (/ shipNOx /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_TMPX_GROUP = (/ shipNOx /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_OC_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_OC_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (3) :: &
    PPM25_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25 /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_PPM25_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25 /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_PPM25_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25 /)
  
  integer, public, target, save, dimension (4) :: &
    PPM10_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25, ffire_c /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_PPM10_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25, ffire_c /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_PPM10_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25, ffire_c /)
  
  integer, public, target, save, dimension (13) :: &
    WDEP_NONVOLPCM_GROUP = (/  &
      ffire_OM, ffire_BC, POM_f_wood, POM_c_wood, POM_f_ffuel,  &
      POM_c_ffuel, EC_f_wood_new, EC_f_wood_age, EC_c_wood,  &
      EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (13) :: &
    DDEP_NONVOLPCM_GROUP = (/  &
      ffire_OM, ffire_BC, POM_f_wood, POM_c_wood, POM_f_ffuel,  &
      POM_c_ffuel, EC_f_wood_new, EC_f_wood_age, EC_c_wood,  &
      EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_NVABSOM_GROUP = (/ ffire_OM, POM_f_wood, POM_f_ffuel, SQT_SOA_NV /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_NVABSOM_GROUP = (/ ffire_OM, POM_f_wood, POM_f_ffuel, SQT_SOA_NV /)
  
  integer, public, target, save, dimension (1) :: &
    FBBPOA25_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_FBBPOA25_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_FBBPOA25_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (5) :: &
    EC_F_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_EC_F_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_EC_F_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    FFIREBC_GROUP = (/ ffire_BC /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_FFIREBC_GROUP = (/ ffire_BC /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_FFIREBC_GROUP = (/ ffire_BC /)
  
  integer, public, target, save, dimension (5) :: &
    ECFINE_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_ECFINE_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_ECFINE_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (6) :: &
    DUST_GROUP = (/  &
      Dust_road_f, Dust_road_c, Dust_wb_f, Dust_wb_c, Dust_sah_f,  &
      Dust_sah_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    WDEP_DUST_GROUP = (/  &
      Dust_road_f, Dust_road_c, Dust_wb_f, Dust_wb_c, Dust_sah_f,  &
      Dust_sah_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_DUST_GROUP = (/  &
      Dust_road_f, Dust_road_c, Dust_wb_f, Dust_wb_c, Dust_sah_f,  &
      Dust_sah_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    DUST_ANT_F_GROUP = (/ Dust_road_f /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DUST_ANT_F_GROUP = (/ Dust_road_f /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DUST_ANT_F_GROUP = (/ Dust_road_f /)
  
  integer, public, target, save, dimension (1) :: &
    DUST_ANT_C_GROUP = (/ Dust_road_c /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DUST_ANT_C_GROUP = (/ Dust_road_c /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DUST_ANT_C_GROUP = (/ Dust_road_c /)
  
  integer, public, target, save, dimension (2) :: &
    DUST_NAT_F_GROUP = (/ Dust_wb_f, Dust_sah_f /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DUST_NAT_F_GROUP = (/ Dust_wb_f, Dust_sah_f /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DUST_NAT_F_GROUP = (/ Dust_wb_f, Dust_sah_f /)
  
  integer, public, target, save, dimension (2) :: &
    DUST_NAT_C_GROUP = (/ Dust_wb_c, Dust_sah_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DUST_NAT_C_GROUP = (/ Dust_wb_c, Dust_sah_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DUST_NAT_C_GROUP = (/ Dust_wb_c, Dust_sah_c /)
  
  integer, public, target, save, dimension (2) :: &
    ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (8) :: &
    PPM25_GROUP = (/  &
      POM_f_wood, POM_f_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_f_ffuel_new, EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (8) :: &
    WDEP_PPM25_GROUP = (/  &
      POM_f_wood, POM_f_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_f_ffuel_new, EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (8) :: &
    DDEP_PPM25_GROUP = (/  &
      POM_f_wood, POM_f_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_f_ffuel_new, EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    PPM10_GROUP = (/  &
      POM_f_wood, POM_c_wood, POM_f_ffuel, POM_c_ffuel,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    WDEP_PPM10_GROUP = (/  &
      POM_f_wood, POM_c_wood, POM_f_ffuel, POM_c_ffuel,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    DDEP_PPM10_GROUP = (/  &
      POM_f_wood, POM_c_wood, POM_f_ffuel, POM_c_ffuel,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    NVWOODOC25_GROUP = (/ POM_f_wood /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVWOODOC25_GROUP = (/ POM_f_wood /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVWOODOC25_GROUP = (/ POM_f_wood /)
  
  integer, public, target, save, dimension (6) :: &
    PPM_C_GROUP = (/  &
      POM_c_wood, POM_c_ffuel, EC_c_wood, EC_c_ffuel, pSO4c,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    WDEP_PPM_C_GROUP = (/  &
      POM_c_wood, POM_c_ffuel, EC_c_wood, EC_c_ffuel, pSO4c,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_PPM_C_GROUP = (/  &
      POM_c_wood, POM_c_ffuel, EC_c_wood, EC_c_ffuel, pSO4c,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    NVWOODOC_COARSE_GROUP = (/ POM_c_wood /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVWOODOC_COARSE_GROUP = (/ POM_c_wood /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVWOODOC_COARSE_GROUP = (/ POM_c_wood /)
  
  integer, public, target, save, dimension (2) :: &
    OMCOARSE_GROUP = (/ POM_c_wood, POM_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_OMCOARSE_GROUP = (/ POM_c_wood, POM_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_OMCOARSE_GROUP = (/ POM_c_wood, POM_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    NVFFUELOC25_GROUP = (/ POM_f_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVFFUELOC25_GROUP = (/ POM_f_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVFFUELOC25_GROUP = (/ POM_f_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    PM10ANTHR_GROUP = (/ POM_c_ffuel, EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_PM10ANTHR_GROUP = (/ POM_c_ffuel, EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_PM10ANTHR_GROUP = (/ POM_c_ffuel, EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    NVFFUELOC_COARSE_GROUP = (/ POM_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVFFUELOC_COARSE_GROUP = (/ POM_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVFFUELOC_COARSE_GROUP = (/ POM_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    WOODEC_GROUP = (/ EC_f_wood_new, EC_f_wood_age, EC_c_wood /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_WOODEC_GROUP = (/ EC_f_wood_new, EC_f_wood_age, EC_c_wood /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_WOODEC_GROUP = (/ EC_f_wood_new, EC_f_wood_age, EC_c_wood /)
  
  integer, public, target, save, dimension (2) :: &
    WOODECFINE_GROUP = (/ EC_f_wood_new, EC_f_wood_age /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_WOODECFINE_GROUP = (/ EC_f_wood_new, EC_f_wood_age /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_WOODECFINE_GROUP = (/ EC_f_wood_new, EC_f_wood_age /)
  
  integer, public, target, save, dimension (2) :: &
    ECCOARSE_GROUP = (/ EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_ECCOARSE_GROUP = (/ EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_ECCOARSE_GROUP = (/ EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    FFUELEC_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_FFUELEC_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_FFUELEC_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    FFUELECFINE_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_FFUELECFINE_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_FFUELECFINE_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age /)
  
  integer, public, target, save, dimension (5) :: &
    POLLEN_GROUP = (/  &
      POLLEN_BIRCH, POLLEN_OLIVE, POLLEN_ALDER, POLLEN_RWEED,  &
      POLLEN_GRASS  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_POLLEN_GROUP = (/  &
      POLLEN_BIRCH, POLLEN_OLIVE, POLLEN_ALDER, POLLEN_RWEED,  &
      POLLEN_GRASS  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_POLLEN_GROUP = (/  &
      POLLEN_BIRCH, POLLEN_OLIVE, POLLEN_ALDER, POLLEN_RWEED,  &
      POLLEN_GRASS  &
    /)
  
  integer, public, target, save, dimension (20) :: &
    CSTAR_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3  &
    /)
  
  real, public, target, save, dimension (20) :: &
    CSTAR_GROUP_FACTORS = (/  &
      0.1, 1.0, 10.0, 1.0e2, 1.0e3, 0.1, 1.0, 10.0, 1.0e2, 1.0e3,  &
      0.1, 1.0, 10.0, 1.0e2, 1.0e3, 0.1, 1.0, 10.0, 1.0e2, 1.0e3  &
    /)
  
  integer, public, target, save, dimension (20) :: &
    DELTAH_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3  &
    /)
  
  real, public, target, save, dimension (20) :: &
    DELTAH_GROUP_FACTORS = (/  &
      30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0,  &
      30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0  &
    /)
  
  integer, public, target, save, dimension (26) :: &
    EXTINC_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, OM25_p, ffire_BC, ffire_remPPM25,  &
      ffire_c, SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c,  &
      Dust_wb_f, Dust_wb_c, Dust_sah_f, Dust_sah_c,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  character(len=TXTLEN_SHORT), public, target, save, dimension (26) :: &
    EXTINC_GROUP_MAPBACK = [ character(len=TXTLEN_SHORT) :: &
    "SO4", "NO3f", "NO3c", "NH4f", "OC", "EC", "DDf", "DDc",  &
      "SSf", "SSc", "DDf", "DDc", "DDf", "DDc", "DDf", "DDc",  &
      "ECn", "ECa", "EC", "ECn", "ECa", "EC", "SO4", "SO4",  &
      "DDf", "DDc"  &
    ]

contains
  
  subroutine Init_ChemGroups()
    
    chemgroups(1)%name="RO2"
    chemgroups(1)%specs=>RO2_GROUP
    
    chemgroups(2)%name="DAOBS"
    chemgroups(2)%specs=>DAOBS_GROUP
    
    chemgroups(3)%name="DDEP_DAOBS"
    chemgroups(3)%specs=>DDEP_DAOBS_GROUP
    
    chemgroups(4)%name="OX"
    chemgroups(4)%specs=>OX_GROUP
    
    chemgroups(5)%name="DDEP_OX"
    chemgroups(5)%specs=>DDEP_OX_GROUP
    
    chemgroups(6)%name="NOX"
    chemgroups(6)%specs=>NOX_GROUP
    
    chemgroups(7)%name="OXN"
    chemgroups(7)%specs=>OXN_GROUP
    
    chemgroups(8)%name="DDEP_NOX"
    chemgroups(8)%specs=>DDEP_NOX_GROUP
    
    chemgroups(9)%name="DDEP_OXN"
    chemgroups(9)%specs=>DDEP_OXN_GROUP
    
    chemgroups(10)%name="WDEP_OXN"
    chemgroups(10)%specs=>WDEP_OXN_GROUP
    
    chemgroups(11)%name="HSTAR_1P0E5"
    chemgroups(11)%specs=>HSTAR_1P0E5_GROUP
    
    chemgroups(12)%name="WDEP_HSTAR_1P0E5"
    chemgroups(12)%specs=>WDEP_HSTAR_1P0E5_GROUP
    
    chemgroups(13)%name="DDEP_HSTAR_1P0E5"
    chemgroups(13)%specs=>DDEP_HSTAR_1P0E5_GROUP
    
    chemgroups(14)%name="F0_1P0"
    chemgroups(14)%specs=>F0_1P0_GROUP
    
    chemgroups(15)%name="WDEP_F0_1P0"
    chemgroups(15)%specs=>WDEP_F0_1P0_GROUP
    
    chemgroups(16)%name="DDEP_F0_1P0"
    chemgroups(16)%specs=>DDEP_F0_1P0_GROUP
    
    chemgroups(17)%name="DRX_1P36"
    chemgroups(17)%specs=>DRX_1P36_GROUP
    
    chemgroups(18)%name="WDEP_DRX_1P36"
    chemgroups(18)%specs=>WDEP_DRX_1P36_GROUP
    
    chemgroups(19)%name="DDEP_DRX_1P36"
    chemgroups(19)%specs=>DDEP_DRX_1P36_GROUP
    
    chemgroups(20)%name="HSTAR_2P6E5"
    chemgroups(20)%specs=>HSTAR_2P6E5_GROUP
    
    chemgroups(21)%name="WDEP_HSTAR_2P6E5"
    chemgroups(21)%specs=>WDEP_HSTAR_2P6E5_GROUP
    
    chemgroups(22)%name="DDEP_HSTAR_2P6E5"
    chemgroups(22)%specs=>DDEP_HSTAR_2P6E5_GROUP
    
    chemgroups(23)%name="F0_0P5"
    chemgroups(23)%specs=>F0_0P5_GROUP
    
    chemgroups(24)%name="WDEP_F0_0P5"
    chemgroups(24)%specs=>WDEP_F0_0P5_GROUP
    
    chemgroups(25)%name="DDEP_F0_0P5"
    chemgroups(25)%specs=>DDEP_F0_0P5_GROUP
    
    chemgroups(26)%name="DRX_1P6"
    chemgroups(26)%specs=>DRX_1P6_GROUP
    
    chemgroups(27)%name="WDEP_DRX_1P6"
    chemgroups(27)%specs=>WDEP_DRX_1P6_GROUP
    
    chemgroups(28)%name="DDEP_DRX_1P6"
    chemgroups(28)%specs=>DDEP_DRX_1P6_GROUP
    
    chemgroups(29)%name="HSTAR_6P0E4"
    chemgroups(29)%specs=>HSTAR_6P0E4_GROUP
    
    chemgroups(30)%name="WDEP_HSTAR_6P0E4"
    chemgroups(30)%specs=>WDEP_HSTAR_6P0E4_GROUP
    
    chemgroups(31)%name="DDEP_HSTAR_6P0E4"
    chemgroups(31)%specs=>DDEP_HSTAR_6P0E4_GROUP
    
    chemgroups(32)%name="DRX_2P1"
    chemgroups(32)%specs=>DRX_2P1_GROUP
    
    chemgroups(33)%name="WDEP_DRX_2P1"
    chemgroups(33)%specs=>WDEP_DRX_2P1_GROUP
    
    chemgroups(34)%name="DDEP_DRX_2P1"
    chemgroups(34)%specs=>DDEP_DRX_2P1_GROUP
    
    chemgroups(35)%name="BVOC"
    chemgroups(35)%specs=>BVOC_GROUP
    
    chemgroups(36)%name="RCHO"
    chemgroups(36)%specs=>RCHO_GROUP
    
    chemgroups(37)%name="WDEP_RCHO"
    chemgroups(37)%specs=>WDEP_RCHO_GROUP
    
    chemgroups(38)%name="DDEP_RCHO"
    chemgroups(38)%specs=>DDEP_RCHO_GROUP
    
    chemgroups(39)%name="CARBONYL"
    chemgroups(39)%specs=>CARBONYL_GROUP
    
    chemgroups(40)%name="WDEP_CARBONYL"
    chemgroups(40)%specs=>WDEP_CARBONYL_GROUP
    
    chemgroups(41)%name="DDEP_CARBONYL"
    chemgroups(41)%specs=>DDEP_CARBONYL_GROUP
    
    chemgroups(42)%name="HSTAR_3P2E3"
    chemgroups(42)%specs=>HSTAR_3P2E3_GROUP
    
    chemgroups(43)%name="WDEP_HSTAR_3P2E3"
    chemgroups(43)%specs=>WDEP_HSTAR_3P2E3_GROUP
    
    chemgroups(44)%name="DDEP_HSTAR_3P2E3"
    chemgroups(44)%specs=>DDEP_HSTAR_3P2E3_GROUP
    
    chemgroups(45)%name="F0_0P2"
    chemgroups(45)%specs=>F0_0P2_GROUP
    
    chemgroups(46)%name="WDEP_F0_0P2"
    chemgroups(46)%specs=>WDEP_F0_0P2_GROUP
    
    chemgroups(47)%name="DDEP_F0_0P2"
    chemgroups(47)%specs=>DDEP_F0_0P2_GROUP
    
    chemgroups(48)%name="DRX_1P4"
    chemgroups(48)%specs=>DRX_1P4_GROUP
    
    chemgroups(49)%name="WDEP_DRX_1P4"
    chemgroups(49)%specs=>WDEP_DRX_1P4_GROUP
    
    chemgroups(50)%name="DDEP_DRX_1P4"
    chemgroups(50)%specs=>DDEP_DRX_1P4_GROUP
    
    chemgroups(51)%name="HSTAR_1P3E1"
    chemgroups(51)%specs=>HSTAR_1P3E1_GROUP
    
    chemgroups(52)%name="DDEP_HSTAR_1P3E1"
    chemgroups(52)%specs=>DDEP_HSTAR_1P3E1_GROUP
    
    chemgroups(53)%name="F0_0P05"
    chemgroups(53)%specs=>F0_0P05_GROUP
    
    chemgroups(54)%name="DDEP_F0_0P05"
    chemgroups(54)%specs=>DDEP_F0_0P05_GROUP
    
    chemgroups(55)%name="HSTAR_5P0E0"
    chemgroups(55)%specs=>HSTAR_5P0E0_GROUP
    
    chemgroups(56)%name="DDEP_HSTAR_5P0E0"
    chemgroups(56)%specs=>DDEP_HSTAR_5P0E0_GROUP
    
    chemgroups(57)%name="DRX_2P6"
    chemgroups(57)%specs=>DRX_2P6_GROUP
    
    chemgroups(58)%name="DDEP_DRX_2P6"
    chemgroups(58)%specs=>DDEP_DRX_2P6_GROUP
    
    chemgroups(59)%name="HSTAR_2P0E1"
    chemgroups(59)%specs=>HSTAR_2P0E1_GROUP
    
    chemgroups(60)%name="DDEP_HSTAR_2P0E1"
    chemgroups(60)%specs=>DDEP_HSTAR_2P0E1_GROUP
    
    chemgroups(61)%name="DRX_2P7"
    chemgroups(61)%specs=>DRX_2P7_GROUP
    
    chemgroups(62)%name="DDEP_DRX_2P7"
    chemgroups(62)%specs=>DDEP_DRX_2P7_GROUP
    
    chemgroups(63)%name="HSTAR_8P0E3"
    chemgroups(63)%specs=>HSTAR_8P0E3_GROUP
    
    chemgroups(64)%name="WDEP_HSTAR_8P0E3"
    chemgroups(64)%specs=>WDEP_HSTAR_8P0E3_GROUP
    
    chemgroups(65)%name="DDEP_HSTAR_8P0E3"
    chemgroups(65)%specs=>DDEP_HSTAR_8P0E3_GROUP
    
    chemgroups(66)%name="WDEP_F0_0P05"
    chemgroups(66)%specs=>WDEP_F0_0P05_GROUP
    
    chemgroups(67)%name="WDEP_DRX_2P6"
    chemgroups(67)%specs=>WDEP_DRX_2P6_GROUP
    
    chemgroups(68)%name="HSTAR_3P0E5"
    chemgroups(68)%specs=>HSTAR_3P0E5_GROUP
    
    chemgroups(69)%name="WDEP_HSTAR_3P0E5"
    chemgroups(69)%specs=>WDEP_HSTAR_3P0E5_GROUP
    
    chemgroups(70)%name="DDEP_HSTAR_3P0E5"
    chemgroups(70)%specs=>DDEP_HSTAR_3P0E5_GROUP
    
    chemgroups(71)%name="F0_0P0"
    chemgroups(71)%specs=>F0_0P0_GROUP
    
    chemgroups(72)%name="WDEP_F0_0P0"
    chemgroups(72)%specs=>WDEP_F0_0P0_GROUP
    
    chemgroups(73)%name="DDEP_F0_0P0"
    chemgroups(73)%specs=>DDEP_F0_0P0_GROUP
    
    chemgroups(74)%name="HSTAR_2P4E4"
    chemgroups(74)%specs=>HSTAR_2P4E4_GROUP
    
    chemgroups(75)%name="WDEP_HSTAR_2P4E4"
    chemgroups(75)%specs=>WDEP_HSTAR_2P4E4_GROUP
    
    chemgroups(76)%name="DDEP_HSTAR_2P4E4"
    chemgroups(76)%specs=>DDEP_HSTAR_2P4E4_GROUP
    
    chemgroups(77)%name="DRX_2P5"
    chemgroups(77)%specs=>DRX_2P5_GROUP
    
    chemgroups(78)%name="WDEP_DRX_2P5"
    chemgroups(78)%specs=>WDEP_DRX_2P5_GROUP
    
    chemgroups(79)%name="DDEP_DRX_2P5"
    chemgroups(79)%specs=>DDEP_DRX_2P5_GROUP
    
    chemgroups(80)%name="HSTAR_7P3E1"
    chemgroups(80)%specs=>HSTAR_7P3E1_GROUP
    
    chemgroups(81)%name="DDEP_HSTAR_7P3E1"
    chemgroups(81)%specs=>DDEP_HSTAR_7P3E1_GROUP
    
    chemgroups(82)%name="DRX_2P8"
    chemgroups(82)%specs=>DRX_2P8_GROUP
    
    chemgroups(83)%name="DDEP_DRX_2P8"
    chemgroups(83)%specs=>DDEP_DRX_2P8_GROUP
    
    chemgroups(84)%name="HSTAR_6P0E5"
    chemgroups(84)%specs=>HSTAR_6P0E5_GROUP
    
    chemgroups(85)%name="WDEP_HSTAR_6P0E5"
    chemgroups(85)%specs=>WDEP_HSTAR_6P0E5_GROUP
    
    chemgroups(86)%name="DDEP_HSTAR_6P0E5"
    chemgroups(86)%specs=>DDEP_HSTAR_6P0E5_GROUP
    
    chemgroups(87)%name="DRX_3P1"
    chemgroups(87)%specs=>DRX_3P1_GROUP
    
    chemgroups(88)%name="WDEP_DRX_3P1"
    chemgroups(88)%specs=>WDEP_DRX_3P1_GROUP
    
    chemgroups(89)%name="DDEP_DRX_3P1"
    chemgroups(89)%specs=>DDEP_DRX_3P1_GROUP
    
    chemgroups(90)%name="ROOH"
    chemgroups(90)%specs=>ROOH_GROUP
    
    chemgroups(91)%name="DDEP_ROOH"
    chemgroups(91)%specs=>DDEP_ROOH_GROUP
    
    chemgroups(92)%name="HSTAR_3P0E2"
    chemgroups(92)%specs=>HSTAR_3P0E2_GROUP
    
    chemgroups(93)%name="DDEP_HSTAR_3P0E2"
    chemgroups(93)%specs=>DDEP_HSTAR_3P0E2_GROUP
    
    chemgroups(94)%name="DRX_1P9"
    chemgroups(94)%specs=>DRX_1P9_GROUP
    
    chemgroups(95)%name="DDEP_DRX_1P9"
    chemgroups(95)%specs=>DDEP_DRX_1P9_GROUP
    
    chemgroups(96)%name="HSTAR_3P3E2"
    chemgroups(96)%specs=>HSTAR_3P3E2_GROUP
    
    chemgroups(97)%name="DDEP_HSTAR_3P3E2"
    chemgroups(97)%specs=>DDEP_HSTAR_3P3E2_GROUP
    
    chemgroups(98)%name="DRX_2P3"
    chemgroups(98)%specs=>DRX_2P3_GROUP
    
    chemgroups(99)%name="DDEP_DRX_2P3"
    chemgroups(99)%specs=>DDEP_DRX_2P3_GROUP
    
    chemgroups(100)%name="HSTAR_6P2E1"
    chemgroups(100)%specs=>HSTAR_6P2E1_GROUP
    
    chemgroups(101)%name="DDEP_HSTAR_6P2E1"
    chemgroups(101)%specs=>DDEP_HSTAR_6P2E1_GROUP
    
    chemgroups(102)%name="DRX_3P0"
    chemgroups(102)%specs=>DRX_3P0_GROUP
    
    chemgroups(103)%name="DDEP_DRX_3P0"
    chemgroups(103)%specs=>DDEP_DRX_3P0_GROUP
    
    chemgroups(104)%name="WDEP_ROOH"
    chemgroups(104)%specs=>WDEP_ROOH_GROUP
    
    chemgroups(105)%name="HSTAR_1P3E6"
    chemgroups(105)%specs=>HSTAR_1P3E6_GROUP
    
    chemgroups(106)%name="WDEP_HSTAR_1P3E6"
    chemgroups(106)%specs=>WDEP_HSTAR_1P3E6_GROUP
    
    chemgroups(107)%name="DDEP_HSTAR_1P3E6"
    chemgroups(107)%specs=>DDEP_HSTAR_1P3E6_GROUP
    
    chemgroups(108)%name="HSTAR_9P0E4"
    chemgroups(108)%specs=>HSTAR_9P0E4_GROUP
    
    chemgroups(109)%name="WDEP_HSTAR_9P0E4"
    chemgroups(109)%specs=>WDEP_HSTAR_9P0E4_GROUP
    
    chemgroups(110)%name="DDEP_HSTAR_9P0E4"
    chemgroups(110)%specs=>DDEP_HSTAR_9P0E4_GROUP
    
    chemgroups(111)%name="HSTAR_1P6E8"
    chemgroups(111)%specs=>HSTAR_1P6E8_GROUP
    
    chemgroups(112)%name="WDEP_HSTAR_1P6E8"
    chemgroups(112)%specs=>WDEP_HSTAR_1P6E8_GROUP
    
    chemgroups(113)%name="DDEP_HSTAR_1P6E8"
    chemgroups(113)%specs=>DDEP_HSTAR_1P6E8_GROUP
    
    chemgroups(114)%name="DRX_3P55"
    chemgroups(114)%specs=>DRX_3P55_GROUP
    
    chemgroups(115)%name="WDEP_DRX_3P55"
    chemgroups(115)%specs=>WDEP_DRX_3P55_GROUP
    
    chemgroups(116)%name="DDEP_DRX_3P55"
    chemgroups(116)%specs=>DDEP_DRX_3P55_GROUP
    
    chemgroups(117)%name="F0_0P3"
    chemgroups(117)%specs=>F0_0P3_GROUP
    
    chemgroups(118)%name="WDEP_F0_0P3"
    chemgroups(118)%specs=>WDEP_F0_0P3_GROUP
    
    chemgroups(119)%name="DDEP_F0_0P3"
    chemgroups(119)%specs=>DDEP_F0_0P3_GROUP
    
    chemgroups(120)%name="HSTAR_1P2E5"
    chemgroups(120)%specs=>HSTAR_1P2E5_GROUP
    
    chemgroups(121)%name="WDEP_HSTAR_1P2E5"
    chemgroups(121)%specs=>WDEP_HSTAR_1P2E5_GROUP
    
    chemgroups(122)%name="DDEP_HSTAR_1P2E5"
    chemgroups(122)%specs=>DDEP_HSTAR_1P2E5_GROUP
    
    chemgroups(123)%name="DRX_3P3"
    chemgroups(123)%specs=>DRX_3P3_GROUP
    
    chemgroups(124)%name="WDEP_DRX_3P3"
    chemgroups(124)%specs=>WDEP_DRX_3P3_GROUP
    
    chemgroups(125)%name="DDEP_DRX_3P3"
    chemgroups(125)%specs=>DDEP_DRX_3P3_GROUP
    
    chemgroups(126)%name="DRX_3P2"
    chemgroups(126)%specs=>DRX_3P2_GROUP
    
    chemgroups(127)%name="WDEP_DRX_3P2"
    chemgroups(127)%specs=>WDEP_DRX_3P2_GROUP
    
    chemgroups(128)%name="DDEP_DRX_3P2"
    chemgroups(128)%specs=>DDEP_DRX_3P2_GROUP
    
    chemgroups(129)%name="HSTAR_3P5E8"
    chemgroups(129)%specs=>HSTAR_3P5E8_GROUP
    
    chemgroups(130)%name="WDEP_HSTAR_3P5E8"
    chemgroups(130)%specs=>WDEP_HSTAR_3P5E8_GROUP
    
    chemgroups(131)%name="DDEP_HSTAR_3P5E8"
    chemgroups(131)%specs=>DDEP_HSTAR_3P5E8_GROUP
    
    chemgroups(132)%name="HSTAR_1P4E8"
    chemgroups(132)%specs=>HSTAR_1P4E8_GROUP
    
    chemgroups(133)%name="WDEP_HSTAR_1P4E8"
    chemgroups(133)%specs=>WDEP_HSTAR_1P4E8_GROUP
    
    chemgroups(134)%name="DDEP_HSTAR_1P4E8"
    chemgroups(134)%specs=>DDEP_HSTAR_1P4E8_GROUP
    
    chemgroups(135)%name="DRX_4P1"
    chemgroups(135)%specs=>DRX_4P1_GROUP
    
    chemgroups(136)%name="WDEP_DRX_4P1"
    chemgroups(136)%specs=>WDEP_DRX_4P1_GROUP
    
    chemgroups(137)%name="DDEP_DRX_4P1"
    chemgroups(137)%specs=>DDEP_DRX_4P1_GROUP
    
    chemgroups(138)%name="PEROXYACID"
    chemgroups(138)%specs=>PEROXYACID_GROUP
    
    chemgroups(139)%name="WDEP_PEROXYACID"
    chemgroups(139)%specs=>WDEP_PEROXYACID_GROUP
    
    chemgroups(140)%name="DDEP_PEROXYACID"
    chemgroups(140)%specs=>DDEP_PEROXYACID_GROUP
    
    chemgroups(141)%name="HSTAR_8P3E2"
    chemgroups(141)%specs=>HSTAR_8P3E2_GROUP
    
    chemgroups(142)%name="WDEP_HSTAR_8P3E2"
    chemgroups(142)%specs=>WDEP_HSTAR_8P3E2_GROUP
    
    chemgroups(143)%name="DDEP_HSTAR_8P3E2"
    chemgroups(143)%specs=>DDEP_HSTAR_8P3E2_GROUP
    
    chemgroups(144)%name="DRX_2P4"
    chemgroups(144)%specs=>DRX_2P4_GROUP
    
    chemgroups(145)%name="WDEP_DRX_2P4"
    chemgroups(145)%specs=>WDEP_DRX_2P4_GROUP
    
    chemgroups(146)%name="DDEP_DRX_2P4"
    chemgroups(146)%specs=>DDEP_DRX_2P4_GROUP
    
    chemgroups(147)%name="HSTAR_1P5E6"
    chemgroups(147)%specs=>HSTAR_1P5E6_GROUP
    
    chemgroups(148)%name="WDEP_HSTAR_1P5E6"
    chemgroups(148)%specs=>WDEP_HSTAR_1P5E6_GROUP
    
    chemgroups(149)%name="DDEP_HSTAR_1P5E6"
    chemgroups(149)%specs=>DDEP_HSTAR_1P5E6_GROUP
    
    chemgroups(150)%name="DRX_3P47"
    chemgroups(150)%specs=>DRX_3P47_GROUP
    
    chemgroups(151)%name="WDEP_DRX_3P47"
    chemgroups(151)%specs=>WDEP_DRX_3P47_GROUP
    
    chemgroups(152)%name="DDEP_DRX_3P47"
    chemgroups(152)%specs=>DDEP_DRX_3P47_GROUP
    
    chemgroups(153)%name="EPOXIDE"
    chemgroups(153)%specs=>EPOXIDE_GROUP
    
    chemgroups(154)%name="WDEP_EPOXIDE"
    chemgroups(154)%specs=>WDEP_EPOXIDE_GROUP
    
    chemgroups(155)%name="DDEP_EPOXIDE"
    chemgroups(155)%specs=>DDEP_EPOXIDE_GROUP
    
    chemgroups(156)%name="HSTAR_0P0E0"
    chemgroups(156)%specs=>HSTAR_0P0E0_GROUP
    
    chemgroups(157)%name="DDEP_HSTAR_0P0E0"
    chemgroups(157)%specs=>DDEP_HSTAR_0P0E0_GROUP
    
    chemgroups(158)%name="HSTAR_5P5E3"
    chemgroups(158)%specs=>HSTAR_5P5E3_GROUP
    
    chemgroups(159)%name="WDEP_HSTAR_5P5E3"
    chemgroups(159)%specs=>WDEP_HSTAR_5P5E3_GROUP
    
    chemgroups(160)%name="DDEP_HSTAR_5P5E3"
    chemgroups(160)%specs=>DDEP_HSTAR_5P5E3_GROUP
    
    chemgroups(161)%name="WDEP_DRX_2P7"
    chemgroups(161)%specs=>WDEP_DRX_2P7_GROUP
    
    chemgroups(162)%name="HSTAR_5P0E4"
    chemgroups(162)%specs=>HSTAR_5P0E4_GROUP
    
    chemgroups(163)%name="WDEP_HSTAR_5P0E4"
    chemgroups(163)%specs=>WDEP_HSTAR_5P0E4_GROUP
    
    chemgroups(164)%name="DDEP_HSTAR_5P0E4"
    chemgroups(164)%specs=>DDEP_HSTAR_5P0E4_GROUP
    
    chemgroups(165)%name="DRX_3P6"
    chemgroups(165)%specs=>DRX_3P6_GROUP
    
    chemgroups(166)%name="WDEP_DRX_3P6"
    chemgroups(166)%specs=>WDEP_DRX_3P6_GROUP
    
    chemgroups(167)%name="DDEP_DRX_3P6"
    chemgroups(167)%specs=>DDEP_DRX_3P6_GROUP
    
    chemgroups(168)%name="PANS"
    chemgroups(168)%specs=>PANS_GROUP
    
    chemgroups(169)%name="DDEP_PANS"
    chemgroups(169)%specs=>DDEP_PANS_GROUP
    
    chemgroups(170)%name="HSTAR_3P0E0"
    chemgroups(170)%specs=>HSTAR_3P0E0_GROUP
    
    chemgroups(171)%name="DDEP_HSTAR_3P0E0"
    chemgroups(171)%specs=>DDEP_HSTAR_3P0E0_GROUP
    
    chemgroups(172)%name="DRX_3P4"
    chemgroups(172)%specs=>DRX_3P4_GROUP
    
    chemgroups(173)%name="DDEP_DRX_3P4"
    chemgroups(173)%specs=>DDEP_DRX_3P4_GROUP
    
    chemgroups(174)%name="MONOTERP"
    chemgroups(174)%specs=>MONOTERP_GROUP
    
    chemgroups(175)%name="DRX_4P5"
    chemgroups(175)%specs=>DRX_4P5_GROUP
    
    chemgroups(176)%name="WDEP_DRX_4P5"
    chemgroups(176)%specs=>WDEP_DRX_4P5_GROUP
    
    chemgroups(177)%name="DDEP_DRX_4P5"
    chemgroups(177)%specs=>DDEP_DRX_4P5_GROUP
    
    chemgroups(178)%name="SOX"
    chemgroups(178)%specs=>SOX_GROUP
    
    chemgroups(179)%name="WDEP_SOX"
    chemgroups(179)%specs=>WDEP_SOX_GROUP
    
    chemgroups(180)%name="DDEP_SOX"
    chemgroups(180)%specs=>DDEP_SOX_GROUP
    
    chemgroups(181)%name="PM10"
    chemgroups(181)%specs=>PM10_GROUP
    
    chemgroups(182)%name="WDEP_PM10"
    chemgroups(182)%specs=>WDEP_PM10_GROUP
    
    chemgroups(183)%name="DDEP_PM10"
    chemgroups(183)%specs=>DDEP_PM10_GROUP
    
    chemgroups(184)%name="PMFINE"
    chemgroups(184)%specs=>PMFINE_GROUP
    
    chemgroups(185)%name="WDEP_PMFINE"
    chemgroups(185)%specs=>WDEP_PMFINE_GROUP
    
    chemgroups(186)%name="DDEP_PMFINE"
    chemgroups(186)%specs=>DDEP_PMFINE_GROUP
    
    chemgroups(187)%name="SIA"
    chemgroups(187)%specs=>SIA_GROUP
    
    chemgroups(188)%name="WDEP_SIA"
    chemgroups(188)%specs=>WDEP_SIA_GROUP
    
    chemgroups(189)%name="DDEP_SIA"
    chemgroups(189)%specs=>DDEP_SIA_GROUP
    
    chemgroups(190)%name="RDN"
    chemgroups(190)%specs=>RDN_GROUP
    
    chemgroups(191)%name="WDEP_RDN"
    chemgroups(191)%specs=>WDEP_RDN_GROUP
    
    chemgroups(192)%name="DDEP_RDN"
    chemgroups(192)%specs=>DDEP_RDN_GROUP
    
    chemgroups(193)%name="PNO3"
    chemgroups(193)%specs=>PNO3_GROUP
    
    chemgroups(194)%name="WDEP_PNO3"
    chemgroups(194)%specs=>WDEP_PNO3_GROUP
    
    chemgroups(195)%name="DDEP_PNO3"
    chemgroups(195)%specs=>DDEP_PNO3_GROUP
    
    chemgroups(196)%name="PMCOARSE"
    chemgroups(196)%specs=>PMCOARSE_GROUP
    
    chemgroups(197)%name="WDEP_PMCOARSE"
    chemgroups(197)%specs=>WDEP_PMCOARSE_GROUP
    
    chemgroups(198)%name="DDEP_PMCOARSE"
    chemgroups(198)%specs=>DDEP_PMCOARSE_GROUP
    
    chemgroups(199)%name="OM25"
    chemgroups(199)%specs=>OM25_GROUP
    
    chemgroups(200)%name="NONVOLPCM"
    chemgroups(200)%specs=>NONVOLPCM_GROUP
    
    chemgroups(201)%name="NVABSOM"
    chemgroups(201)%specs=>NVABSOM_GROUP
    
    chemgroups(202)%name="OC"
    chemgroups(202)%specs=>OC_GROUP
    
    chemgroups(203)%name="WDEP_OM25"
    chemgroups(203)%specs=>WDEP_OM25_GROUP
    
    chemgroups(204)%name="DDEP_OM25"
    chemgroups(204)%specs=>DDEP_OM25_GROUP
    
    chemgroups(205)%name="PCM"
    chemgroups(205)%specs=>PCM_GROUP
    
    chemgroups(206)%name="WDEP_PCM"
    chemgroups(206)%specs=>WDEP_PCM_GROUP
    
    chemgroups(207)%name="DDEP_PCM"
    chemgroups(207)%specs=>DDEP_PCM_GROUP
    
    chemgroups(208)%name="ASOA"
    chemgroups(208)%specs=>ASOA_GROUP
    
    chemgroups(209)%name="WDEP_ASOA"
    chemgroups(209)%specs=>WDEP_ASOA_GROUP
    
    chemgroups(210)%name="DDEP_ASOA"
    chemgroups(210)%specs=>DDEP_ASOA_GROUP
    
    chemgroups(211)%name="BSOA"
    chemgroups(211)%specs=>BSOA_GROUP
    
    chemgroups(212)%name="WDEP_BSOA"
    chemgroups(212)%specs=>WDEP_BSOA_GROUP
    
    chemgroups(213)%name="DDEP_BSOA"
    chemgroups(213)%specs=>DDEP_BSOA_GROUP
    
    chemgroups(214)%name="TMPX"
    chemgroups(214)%specs=>TMPX_GROUP
    
    chemgroups(215)%name="DDEP_TMPX"
    chemgroups(215)%specs=>DDEP_TMPX_GROUP
    
    chemgroups(216)%name="WDEP_OC"
    chemgroups(216)%specs=>WDEP_OC_GROUP
    
    chemgroups(217)%name="DDEP_OC"
    chemgroups(217)%specs=>DDEP_OC_GROUP
    
    chemgroups(218)%name="PPM25_FIRE"
    chemgroups(218)%specs=>PPM25_FIRE_GROUP
    
    chemgroups(219)%name="WDEP_PPM25_FIRE"
    chemgroups(219)%specs=>WDEP_PPM25_FIRE_GROUP
    
    chemgroups(220)%name="DDEP_PPM25_FIRE"
    chemgroups(220)%specs=>DDEP_PPM25_FIRE_GROUP
    
    chemgroups(221)%name="PPM10_FIRE"
    chemgroups(221)%specs=>PPM10_FIRE_GROUP
    
    chemgroups(222)%name="WDEP_PPM10_FIRE"
    chemgroups(222)%specs=>WDEP_PPM10_FIRE_GROUP
    
    chemgroups(223)%name="DDEP_PPM10_FIRE"
    chemgroups(223)%specs=>DDEP_PPM10_FIRE_GROUP
    
    chemgroups(224)%name="WDEP_NONVOLPCM"
    chemgroups(224)%specs=>WDEP_NONVOLPCM_GROUP
    
    chemgroups(225)%name="DDEP_NONVOLPCM"
    chemgroups(225)%specs=>DDEP_NONVOLPCM_GROUP
    
    chemgroups(226)%name="WDEP_NVABSOM"
    chemgroups(226)%specs=>WDEP_NVABSOM_GROUP
    
    chemgroups(227)%name="DDEP_NVABSOM"
    chemgroups(227)%specs=>DDEP_NVABSOM_GROUP
    
    chemgroups(228)%name="FBBPOA25"
    chemgroups(228)%specs=>FBBPOA25_GROUP
    
    chemgroups(229)%name="WDEP_FBBPOA25"
    chemgroups(229)%specs=>WDEP_FBBPOA25_GROUP
    
    chemgroups(230)%name="DDEP_FBBPOA25"
    chemgroups(230)%specs=>DDEP_FBBPOA25_GROUP
    
    chemgroups(231)%name="EC_F"
    chemgroups(231)%specs=>EC_F_GROUP
    
    chemgroups(232)%name="WDEP_EC_F"
    chemgroups(232)%specs=>WDEP_EC_F_GROUP
    
    chemgroups(233)%name="DDEP_EC_F"
    chemgroups(233)%specs=>DDEP_EC_F_GROUP
    
    chemgroups(234)%name="FFIREBC"
    chemgroups(234)%specs=>FFIREBC_GROUP
    
    chemgroups(235)%name="WDEP_FFIREBC"
    chemgroups(235)%specs=>WDEP_FFIREBC_GROUP
    
    chemgroups(236)%name="DDEP_FFIREBC"
    chemgroups(236)%specs=>DDEP_FFIREBC_GROUP
    
    chemgroups(237)%name="ECFINE"
    chemgroups(237)%specs=>ECFINE_GROUP
    
    chemgroups(238)%name="WDEP_ECFINE"
    chemgroups(238)%specs=>WDEP_ECFINE_GROUP
    
    chemgroups(239)%name="DDEP_ECFINE"
    chemgroups(239)%specs=>DDEP_ECFINE_GROUP
    
    chemgroups(240)%name="SS"
    chemgroups(240)%specs=>SS_GROUP
    
    chemgroups(241)%name="WDEP_SS"
    chemgroups(241)%specs=>WDEP_SS_GROUP
    
    chemgroups(242)%name="DDEP_SS"
    chemgroups(242)%specs=>DDEP_SS_GROUP
    
    chemgroups(243)%name="DUST"
    chemgroups(243)%specs=>DUST_GROUP
    
    chemgroups(244)%name="WDEP_DUST"
    chemgroups(244)%specs=>WDEP_DUST_GROUP
    
    chemgroups(245)%name="DDEP_DUST"
    chemgroups(245)%specs=>DDEP_DUST_GROUP
    
    chemgroups(246)%name="DUST_ANT_F"
    chemgroups(246)%specs=>DUST_ANT_F_GROUP
    
    chemgroups(247)%name="WDEP_DUST_ANT_F"
    chemgroups(247)%specs=>WDEP_DUST_ANT_F_GROUP
    
    chemgroups(248)%name="DDEP_DUST_ANT_F"
    chemgroups(248)%specs=>DDEP_DUST_ANT_F_GROUP
    
    chemgroups(249)%name="DUST_ANT_C"
    chemgroups(249)%specs=>DUST_ANT_C_GROUP
    
    chemgroups(250)%name="WDEP_DUST_ANT_C"
    chemgroups(250)%specs=>WDEP_DUST_ANT_C_GROUP
    
    chemgroups(251)%name="DDEP_DUST_ANT_C"
    chemgroups(251)%specs=>DDEP_DUST_ANT_C_GROUP
    
    chemgroups(252)%name="DUST_NAT_F"
    chemgroups(252)%specs=>DUST_NAT_F_GROUP
    
    chemgroups(253)%name="WDEP_DUST_NAT_F"
    chemgroups(253)%specs=>WDEP_DUST_NAT_F_GROUP
    
    chemgroups(254)%name="DDEP_DUST_NAT_F"
    chemgroups(254)%specs=>DDEP_DUST_NAT_F_GROUP
    
    chemgroups(255)%name="DUST_NAT_C"
    chemgroups(255)%specs=>DUST_NAT_C_GROUP
    
    chemgroups(256)%name="WDEP_DUST_NAT_C"
    chemgroups(256)%specs=>WDEP_DUST_NAT_C_GROUP
    
    chemgroups(257)%name="DDEP_DUST_NAT_C"
    chemgroups(257)%specs=>DDEP_DUST_NAT_C_GROUP
    
    chemgroups(258)%name="ASH"
    chemgroups(258)%specs=>ASH_GROUP
    
    chemgroups(259)%name="WDEP_ASH"
    chemgroups(259)%specs=>WDEP_ASH_GROUP
    
    chemgroups(260)%name="DDEP_ASH"
    chemgroups(260)%specs=>DDEP_ASH_GROUP
    
    chemgroups(261)%name="PPM25"
    chemgroups(261)%specs=>PPM25_GROUP
    
    chemgroups(262)%name="WDEP_PPM25"
    chemgroups(262)%specs=>WDEP_PPM25_GROUP
    
    chemgroups(263)%name="DDEP_PPM25"
    chemgroups(263)%specs=>DDEP_PPM25_GROUP
    
    chemgroups(264)%name="PPM10"
    chemgroups(264)%specs=>PPM10_GROUP
    
    chemgroups(265)%name="WDEP_PPM10"
    chemgroups(265)%specs=>WDEP_PPM10_GROUP
    
    chemgroups(266)%name="DDEP_PPM10"
    chemgroups(266)%specs=>DDEP_PPM10_GROUP
    
    chemgroups(267)%name="NVWOODOC25"
    chemgroups(267)%specs=>NVWOODOC25_GROUP
    
    chemgroups(268)%name="WDEP_NVWOODOC25"
    chemgroups(268)%specs=>WDEP_NVWOODOC25_GROUP
    
    chemgroups(269)%name="DDEP_NVWOODOC25"
    chemgroups(269)%specs=>DDEP_NVWOODOC25_GROUP
    
    chemgroups(270)%name="PPM_C"
    chemgroups(270)%specs=>PPM_C_GROUP
    
    chemgroups(271)%name="WDEP_PPM_C"
    chemgroups(271)%specs=>WDEP_PPM_C_GROUP
    
    chemgroups(272)%name="DDEP_PPM_C"
    chemgroups(272)%specs=>DDEP_PPM_C_GROUP
    
    chemgroups(273)%name="NVWOODOC_COARSE"
    chemgroups(273)%specs=>NVWOODOC_COARSE_GROUP
    
    chemgroups(274)%name="WDEP_NVWOODOC_COARSE"
    chemgroups(274)%specs=>WDEP_NVWOODOC_COARSE_GROUP
    
    chemgroups(275)%name="DDEP_NVWOODOC_COARSE"
    chemgroups(275)%specs=>DDEP_NVWOODOC_COARSE_GROUP
    
    chemgroups(276)%name="OMCOARSE"
    chemgroups(276)%specs=>OMCOARSE_GROUP
    
    chemgroups(277)%name="WDEP_OMCOARSE"
    chemgroups(277)%specs=>WDEP_OMCOARSE_GROUP
    
    chemgroups(278)%name="DDEP_OMCOARSE"
    chemgroups(278)%specs=>DDEP_OMCOARSE_GROUP
    
    chemgroups(279)%name="NVFFUELOC25"
    chemgroups(279)%specs=>NVFFUELOC25_GROUP
    
    chemgroups(280)%name="WDEP_NVFFUELOC25"
    chemgroups(280)%specs=>WDEP_NVFFUELOC25_GROUP
    
    chemgroups(281)%name="DDEP_NVFFUELOC25"
    chemgroups(281)%specs=>DDEP_NVFFUELOC25_GROUP
    
    chemgroups(282)%name="PM10ANTHR"
    chemgroups(282)%specs=>PM10ANTHR_GROUP
    
    chemgroups(283)%name="WDEP_PM10ANTHR"
    chemgroups(283)%specs=>WDEP_PM10ANTHR_GROUP
    
    chemgroups(284)%name="DDEP_PM10ANTHR"
    chemgroups(284)%specs=>DDEP_PM10ANTHR_GROUP
    
    chemgroups(285)%name="NVFFUELOC_COARSE"
    chemgroups(285)%specs=>NVFFUELOC_COARSE_GROUP
    
    chemgroups(286)%name="WDEP_NVFFUELOC_COARSE"
    chemgroups(286)%specs=>WDEP_NVFFUELOC_COARSE_GROUP
    
    chemgroups(287)%name="DDEP_NVFFUELOC_COARSE"
    chemgroups(287)%specs=>DDEP_NVFFUELOC_COARSE_GROUP
    
    chemgroups(288)%name="WOODEC"
    chemgroups(288)%specs=>WOODEC_GROUP
    
    chemgroups(289)%name="WDEP_WOODEC"
    chemgroups(289)%specs=>WDEP_WOODEC_GROUP
    
    chemgroups(290)%name="DDEP_WOODEC"
    chemgroups(290)%specs=>DDEP_WOODEC_GROUP
    
    chemgroups(291)%name="WOODECFINE"
    chemgroups(291)%specs=>WOODECFINE_GROUP
    
    chemgroups(292)%name="WDEP_WOODECFINE"
    chemgroups(292)%specs=>WDEP_WOODECFINE_GROUP
    
    chemgroups(293)%name="DDEP_WOODECFINE"
    chemgroups(293)%specs=>DDEP_WOODECFINE_GROUP
    
    chemgroups(294)%name="ECCOARSE"
    chemgroups(294)%specs=>ECCOARSE_GROUP
    
    chemgroups(295)%name="WDEP_ECCOARSE"
    chemgroups(295)%specs=>WDEP_ECCOARSE_GROUP
    
    chemgroups(296)%name="DDEP_ECCOARSE"
    chemgroups(296)%specs=>DDEP_ECCOARSE_GROUP
    
    chemgroups(297)%name="FFUELEC"
    chemgroups(297)%specs=>FFUELEC_GROUP
    
    chemgroups(298)%name="WDEP_FFUELEC"
    chemgroups(298)%specs=>WDEP_FFUELEC_GROUP
    
    chemgroups(299)%name="DDEP_FFUELEC"
    chemgroups(299)%specs=>DDEP_FFUELEC_GROUP
    
    chemgroups(300)%name="FFUELECFINE"
    chemgroups(300)%specs=>FFUELECFINE_GROUP
    
    chemgroups(301)%name="WDEP_FFUELECFINE"
    chemgroups(301)%specs=>WDEP_FFUELECFINE_GROUP
    
    chemgroups(302)%name="DDEP_FFUELECFINE"
    chemgroups(302)%specs=>DDEP_FFUELECFINE_GROUP
    
    chemgroups(303)%name="POLLEN"
    chemgroups(303)%specs=>POLLEN_GROUP
    
    chemgroups(304)%name="WDEP_POLLEN"
    chemgroups(304)%specs=>WDEP_POLLEN_GROUP
    
    chemgroups(305)%name="DDEP_POLLEN"
    chemgroups(305)%specs=>DDEP_POLLEN_GROUP
    
    chemgroups_factors(1)%name="CSTAR"
    chemgroups_factors(1)%species=>CSTAR_GROUP
    chemgroups_factors(1)%factors=>CSTAR_GROUP_FACTORS
    
    chemgroups_factors(2)%name="DELTAH"
    chemgroups_factors(2)%species=>DELTAH_GROUP
    chemgroups_factors(2)%factors=>DELTAH_GROUP_FACTORS
    
    chemgroups_maps(1)%name="EXTINC"
    chemgroups_maps(1)%species=>EXTINC_GROUP
    chemgroups_maps(1)%maps=>EXTINC_GROUP_MAPBACK
  
  end subroutine Init_ChemGroups

end module ChemGroups_mod
