! <CM_ChemDims_mod.f90 - A component of the EMEP MSC-W Chemical transport Model, version rv4.32beta>
!*****************************************************************************!
!*
!*  Copyright (C) 2007-2019 met.no
!*
!*  Contact information:
!*  Norwegian Meteorological Institute
!*  Box 43 Blindern
!*  0313 OSLO
!*  NORWAY
!*  email: emep.mscw@met.no
!*  http://www.emep.int
!*
!*    This program is free software: you can redistribute it and/or modify
!*    it under the terms of the GNU General Public License as published by
!*    the Free Software Foundation, either version 3 of the License, or
!*    (at your option) any later version.
!*
!*    This program is distributed in the hope that it will be useful,
!*    but WITHOUT ANY WARRANTY; without even the implied warranty of
!*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!*    GNU General Public License for more details.
!*
!*    You should have received a copy of the GNU General Public License
!*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
!*****************************************************************************!
! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem16x ShipNOx BVOC_EmChem16x Aqueous_EmChem16x Aero2017nx VBS_EmChem16x FFireInert SeaSalt DustExtended Ash_EmChem16x
module ChemDims_mod

  implicit none
  character(len=*),parameter, public :: CM_schemes_ChemDims = " EmChem16x ShipNOx BVOC_EmChem16x Aqueous_EmChem16x Aero2017nx VBS_EmChem16x FFireInert SeaSalt DustExtended Ash_EmChem16x"
  

    ! NSPEC for TOT : All reacting species
    integer, public, parameter :: NSPEC_TOT=128
    
    ! NSPEC for ADV : Advected species
    integer, public, parameter :: NSPEC_ADV=111
    
    ! NSPEC for SHL : Short-lived (non-advected) species
    integer, public, parameter :: NSPEC_SHL=17
    
    ! NSPEC for SEMIVOL : Semi-volatile organic aerosols
    integer, public, parameter :: NSPEC_SEMIVOL=22
        
    ! No. DRY deposition species
    integer, public, parameter :: NDRYDEP_ADV = 68
    
    ! No. WET deposition species
    integer, public, parameter :: NWETDEP_ADV = 59
    
    ! No. rate coefficients
    integer, parameter, public :: NCHEMRATES = 117
    
    ! No. photolysis rates used
    integer, parameter, public :: NPHOTOLRATES = 14
    
    ! No. emission Files
    integer, parameter, public :: NEMIS_File = 7
    
    ! No. emission Specss
    integer, parameter, public :: NEMIS_Specs = 44

end module ChemDims_mod
