character(len=15), save, dimension(NEMIS_Specs), public :: EMIS_Specs = (/ &
  "NO             " &
, "NO2            " &
, "SO2            " &
, "SO4            " &
, "CO             " &
, "NH3            " &
, "C2H6           " &
, "NC4H10         " &
, "C2H4           " &
, "C3H6           " &
, "OXYL           " &
, "BENZENE        " &
, "TOLUENE        " &
, "HCHO           " &
, "CH3CHO         " &
, "MEK            " &
, "C2H5OH         " &
, "CH3OH          " &
, "GLYOX          " &
, "MGLYOX         " &
, "C5H8           " &
, "SHIPNOX        " &
, "FFIRE_OM       " &
, "FFIRE_BC       " &
, "FFIRE_REMPPM25 " &
, "FFIRE_C        " &
, "SEASALT_F      " &
, "SEASALT_C      " &
, "DUST_WB_F      " &
, "DUST_WB_C      " &
, "DUST_ROAD_F    " &
, "DUST_ROAD_C    " &
, "DUST_SAH_F     " &
, "DUST_SAH_C     " &
, "ASH_F          " &
, "ASH_C          " &
, "POM_F_NONRES   " &
, "POM_C_NONRES   " &
, "EC_F_NONRES_NEW" &
, "EC_F_NONRES_AGE" &
, "EC_C_NONRES    " &
, "POM_F_RES      " &
, "EC_F_RES_NEW   " &
, "EC_F_RES_AGE   " &
, "EC_C_RES       " &
, "REMPPM25_RES   " &
, "REMPPM25_NONRES" &
, "REMPPM_C_RES   " &
, "REMPPM_C_NONRES" &
/)
