#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# emep-ctm documentation build configuration file, created by
# sphinx-quickstart on Mon Jan  2 16:11:09 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = '2.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.todo', 'sphinx.ext.mathjax']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

numfig = True
numfig_format={
    'figure':'Figure %s',
    'table':'Table %s',
    'section':'Section %s',
    'code-block':'Listing %s',
}

# Shorthands
rst_epilog = """
.. |O3|    replace:: O\ :sub:`3`
.. |NHx|   replace:: NH\ :sub:`x`
.. |NH3|   replace:: NH\ :sub:`3`
.. |HNO3|  replace:: HNO\ :sub:`3`
.. |SOx|   replace:: SO\ :sub:`x`
.. |SO2|   replace:: SO\ :sub:`2`
.. |SO4|   replace:: SO\ :math:`_4^{2-}`
.. |NOx|   replace:: NO\ :sub:`x`
.. |NO2|   replace:: NO\ :sub:`2`
.. |NO3|   replace:: NO\ :math:`_3^-`
.. |NH4|   replace:: NH\ :math:`_4^+`
.. |PM25|  replace:: PM\ :sub:`2.5`
.. |PMco|  replace:: PM\ :sub:`co`
.. |PM10|  replace:: PM\ :sub:`10`
.. |ugm3|  replace:: :math:`\mu g/m^3`
.. |degC|  replace:: :math:`^\circ C`
.. |ugSm3| replace:: :math:`\mu g(S)/m^3`
.. |ugNm3| replace:: :math:`\mu g(N)/m^3`
.. |ugCm3| replace:: :math:`\mu g(C)/m^3`
.. |mgm2|  replace:: :math:`mg/m^2`
.. |mgSm2| replace:: :math:`mg(S)/m^2`
.. |mgNm2| replace:: :math:`mg(N)/m^2`
.. |mgCm2| replace:: :math:`mg(C)/m^2`
"""

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'emep-ctm'
copyright = '2007-2022 met.no'
author = 'Norwegian Meteorological Institute'
title = "EMEP/MSC-W Model Unofficial User's Guide"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '4.45'
# The full version, including alpha/beta/rc tags.
release = 'rv4_45'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'emep-ctmdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'emep-ctm.tex', title, 'https://github.com/metno/emep-ctm', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'emep-ctm', title, [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'emep-ctm', title,
     author, 'emep-ctm', 'Open Source EMEP/MSC-W model',
     'Miscellaneous'),
]
