# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-merge-conflict" },
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-symlinks" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" }
]


[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.8"
hooks = [
  { id = "ruff-check" },
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "v2.3.1"
hooks = [
  { id = "mypy" }
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.3"
hooks = [
  { id = "codespell" }
]
