  integer, parameter, public ::  NEMIS_BioNat  = 18
  character(len=11), save, dimension(NEMIS_BioNat), public:: &
      EMIS_BioNat =  (/ &
             "C5H8       " &
           , "APINENE    " &
           , "NO         " &
           , "V1702A02B_1" &
           , "V1702A02B_2" &
           , "V1702A02B_3" &
           , "V1702A02B_4" &
           , "V1702A02B_5" &
           , "V1702A02B_6" &
           , "V1702A02B_7" &
           , "V1702A02B_8" &
           , "V1702A02B_9" &
           , "SEASALT_F  " &
           , "SEASALT_C  " &
           , "DUST_WB_F  " &
           , "DUST_WB_C  " &
           , "DUST_ROAD_F" &
           , "DUST_ROAD_C" &
 /)
 